---
name: Data-FormValidator-Constraints-CreditCard
version: 0.02
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: 'Data constraints, using Business::CreditCard'
license: perl
resources:
  license: ~
requires:
  Business::CreditCard: 0.3
  Data::FormValidator: 4
build_requires:
  Test::More: 0
provides:
  Data::FormValidator::Constraints::CreditCard:
    file: lib/Data/FormValidator/Constraints/CreditCard.pm
    version: 0.02
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
